url: mafaldafalcaotvf.github.io

facebook_username: mafaldafalcaotvf
twitter_username: mafalda_falcao
github_username: mafaldafalcaotvf
instagram_username: mafaldafalcaotvf
px500_username: mafaldafalcaotvf
linkedin_username: mafaldafalcaotvf

copyright_note: "2017 by Mafalda Falc√£o Ferreira. All rights reserved."